export const schemaHome = [
  {
    '@context': 'http://schema.org/',
    '@type': 'CreativeWork',
    text: 'Content marketing and advertising agency that drives brand growth',
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Brand Content Production Agency',
    image: 'https://www.redbangle.com/wp-content/uploads/2021/02/logored.png',
    url: 'https://www.redbangle.com/',
    telephone: '9876543210',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress:
        '2nd Floor, Silver Rock, 12, Nandi Durga Road, 1, 1st Main Rd, Bengaluru, Karnataka',
      addressLocality: 'India',
      postalCode: '560046',
      addressCountry: 'IN',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 13.12032,
      longitude: 77.62527,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Brand Content Production Agency',
    alternateName: 'Brand Content Production Agency',
    url: 'https://www.redbangle.com/',
    logo: 'https://www.redbangle.com/wp-content/uploads/2021/02/logored.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '9876543210',
      contactType: 'sales',
      areaServed: 'IN',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.com/wp-content/uploads/2021/02/logored.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.com/',
      image: 'https://www.redbangle.com/wp-content/uploads/2021/02/logored.png',
    },
    headline: 'Brand Content Production Agency',
    datePublished: '2011-01-28T17:15:23+08:00',
    dateModified: '2022-01-28T16:12:29+08:00',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Brand Content Production Agency',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.com/wp-content/uploads/2021/02/logored.png',
      },
    },
  },
  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Integrated Marketing Agency',
    image: 'https://www.redbangle.com/wp-content/uploads/2021/02/logored.png',
    url: 'https://www.redbangle.com/',
    telephone: '9876543210',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress:
        '2nd Floor, Silver Rock, 12, Nandi Durga Road, 1, 1st Main Rd, Bengaluru, Karnataka',
      addressLocality: 'India',
      postalCode: '560046',
      addressCountry: 'IN',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 13.12032,
      longitude: 77.62527,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Integrated Marketing Agency',
    alternateName: 'Integrated Marketing Agency',
    url: 'https://www.redbangle.com/',
    logo: 'https://www.redbangle.com/wp-content/uploads/2021/02/logored.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '9876543210',
      contactType: 'sales',
      areaServed: 'IN',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.com/wp-content/uploads/2021/02/logored.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.com/',
      image: 'https://www.redbangle.com/wp-content/uploads/2021/02/logored.png',
    },
    headline: 'Integrated Marketing Agency',
    datePublished: '2011-01-28T17:15:23+08:00',
    dateModified: '2022-01-28T16:12:29+08:00',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Integrated Marketing Agency',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.com/wp-content/uploads/2021/02/logored.png',
      },
    },
  },
  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Holistic Marketing Agency',
    image: 'https://www.redbangle.com/wp-content/uploads/2021/02/logored.png',
    url: 'https://www.redbangle.com/',
    telephone: '9876543210',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress:
        '2nd Floor, Silver Rock, 12, Nandi Durga Road, 1, 1st Main Rd, Bengaluru, Karnataka',
      addressLocality: 'India',
      postalCode: '560046',
      addressCountry: 'IN',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 13.12032,
      longitude: 77.62527,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Holistic Marketing Agency',
    alternateName: 'Holistic Marketing Agency',
    url: 'https://www.redbangle.com/',
    logo: 'https://www.redbangle.com/wp-content/uploads/2021/02/logored.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '9876543210',
      contactType: 'sales',
      areaServed: 'IN',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },
  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.com/wp-content/uploads/2021/02/logored.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.com/',
      image: 'https://www.redbangle.com/wp-content/uploads/2021/02/logored.png',
    },
    headline: 'Holistic Marketing Agency',
    datePublished: '2011-01-28T17:15:23+08:00',
    dateModified: '2022-01-28T16:12:29+08:00',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Holistic Marketing Agency',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.com/wp-content/uploads/2021/02/logored.png',
      },
    },
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Brand Strategy',
    image: 'https://www.redbangle.com/wp-content/uploads/2021/02/logored.png',
    url: 'https://www.redbangle.com/',
    telephone: '9876543210',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress:
        '2nd Floor, Silver Rock, 12, Nandi Durga Road, 1, 1st Main Rd, Bengaluru, Karnataka',
      addressLocality: 'India',
      postalCode: '560046',
      addressCountry: 'IN',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 13.12032,
      longitude: 77.62527,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Brand Strategy',
    alternateName: 'Brand Strategy',
    url: 'https://www.redbangle.com/',
    logo: 'https://www.redbangle.com/wp-content/uploads/2021/02/logored.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '9876543210',
      contactType: 'sales',
      areaServed: 'IN',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.com/wp-content/uploads/2021/02/logored.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.com/',
      image: 'https://www.redbangle.com/wp-content/uploads/2021/02/logored.png',
    },
    headline: 'Brand Strategy',
    datePublished: '2011-01-28T17:15:23+08:00',
    dateModified: '2022-01-28T16:12:29+08:00',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Brand Strategy',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.com/wp-content/uploads/2021/02/logored.png',
      },
    },
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Content Production Agency',
    image: 'https://www.redbangle.com/wp-content/uploads/2021/02/logored.png',
    url: 'https://www.redbangle.com/',
    telephone: '9876543210',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress:
        '2nd Floor, Silver Rock, 12, Nandi Durga Road, 1, 1st Main Rd, Bengaluru, Karnataka',
      addressLocality: 'India',
      postalCode: '560046',
      addressCountry: 'IN',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 13.12032,
      longitude: 77.62527,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Content Production Agency',
    alternateName: 'Content Production Agency',
    url: 'https://www.redbangle.com/',
    logo: 'https://www.redbangle.com/wp-content/uploads/2021/02/logored.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '9876543210',
      contactType: 'sales',
      areaServed: 'IN',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.com/wp-content/uploads/2021/02/logored.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.com/',
      image: 'https://www.redbangle.com/wp-content/uploads/2021/02/logored.png',
    },
    headline: 'Content Production Agency',
    datePublished: '2011-01-28T17:15:23+08:00',
    dateModified: '2022-01-28T16:12:29+08:00',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Content Production Agency',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.com/wp-content/uploads/2021/02/logored.png',
      },
    },
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Integrated Agency',
    image: 'https://www.redbangle.com/wp-content/uploads/2021/02/logored.png',
    url: 'https://www.redbangle.com/',
    telephone: '9876543210',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress:
        '2nd Floor, Silver Rock, 12, Nandi Durga Road, 1, 1st Main Rd, Bengaluru, Karnataka',
      addressLocality: 'India',
      postalCode: '560046',
      addressCountry: 'IN',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 13.12032,
      longitude: 77.62527,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Integrated Agency',
    alternateName: 'Integrated Agency',
    url: 'https://www.redbangle.com/',
    logo: 'https://www.redbangle.com/wp-content/uploads/2021/02/logored.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '9876543210',
      contactType: 'sales',
      areaServed: 'IN',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.com/wp-content/uploads/2021/02/logored.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.com/',
      image: 'https://www.redbangle.com/wp-content/uploads/2021/02/logored.png',
    },
    headline: 'Integrated Agency',
    datePublished: '2011-01-28T17:15:23+08:00',
    dateModified: '2022-01-28T16:12:29+08:00',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Integrated Agency',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.com/wp-content/uploads/2021/02/logored.png',
      },
    },
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Creative Agency',
    image: 'https://www.redbangle.com/wp-content/uploads/2021/02/logored.png',
    url: 'https://www.redbangle.com/',
    telephone: '9876543210',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress:
        '2nd Floor, Silver Rock, 12, Nandi Durga Road, 1, 1st Main Rd, Bengaluru, Karnataka',
      addressLocality: 'India',
      postalCode: '560046',
      addressCountry: 'IN',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 13.12032,
      longitude: 77.62527,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Creative Agency',
    alternateName: 'Creative Agency',
    url: 'https://www.redbangle.com/',
    logo: 'https://www.redbangle.com/wp-content/uploads/2021/02/logored.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '9876543210',
      contactType: 'sales',
      areaServed: 'IN',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.com/wp-content/uploads/2021/02/logored.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.com/',
      image: 'https://www.redbangle.com/wp-content/uploads/2021/02/logored.png',
    },
    headline: 'Creative Agency',
    datePublished: '2011-01-28T17:15:23+08:00',
    dateModified: '2022-01-28T16:12:29+08:00',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Creative Agency',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.com/wp-content/uploads/2021/02/logored.png',
      },
    },
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Digital Marketing Company',
    image: 'https://www.redbangle.com/wp-content/uploads/2021/02/logored.png',
    url: 'https://www.redbangle.com/',
    telephone: '9876543210',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress:
        '2nd Floor, Silver Rock, 12, Nandi Durga Road, 1, 1st Main Rd, Bengaluru, Karnataka',
      addressLocality: 'India',
      postalCode: '560046',
      addressCountry: 'IN',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 13.12032,
      longitude: 77.62527,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Digital Marketing Company',
    alternateName: 'Digital Marketing Company',
    url: 'https://www.redbangle.com/',
    logo: 'https://www.redbangle.com/wp-content/uploads/2021/02/logored.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '9876543210',
      contactType: 'sales',
      areaServed: 'IN',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.com/wp-content/uploads/2021/02/logored.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.com/',
      image: 'https://www.redbangle.com/wp-content/uploads/2021/02/logored.png',
    },
    headline: 'Digital Marketing Company',
    datePublished: '2011-01-28T17:15:23+08:00',
    dateModified: '2022-01-28T16:12:29+08:00',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Digital Marketing Company',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.com/wp-content/uploads/2021/02/logored.png',
      },
    },
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Advertising Agency',
    image: 'https://www.redbangle.com/wp-content/uploads/2021/02/logored.png',
    url: 'https://www.redbangle.com/',
    telephone: '9876543210',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress:
        '2nd Floor, Silver Rock, 12, Nandi Durga Road, 1, 1st Main Rd, Bengaluru, Karnataka',
      addressLocality: 'India',
      postalCode: '560046',
      addressCountry: 'IN',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 13.12032,
      longitude: 77.62527,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Advertising Agency',
    alternateName: 'Advertising Agency',
    url: 'https://www.redbangle.com/',
    logo: 'https://www.redbangle.com/wp-content/uploads/2021/02/logored.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '9876543210',
      contactType: 'sales',
      areaServed: 'IN',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },
  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.com/wp-content/uploads/2021/02/logored.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.com/',
      image: 'https://www.redbangle.com/wp-content/uploads/2021/02/logored.png',
    },
    headline: 'Advertising Agency',
    datePublished: '2011-01-28T17:15:23+08:00',
    dateModified: '2022-01-28T16:12:29+08:00',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Advertising Agency',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.com/wp-content/uploads/2021/02/logored.png',
      },
    },
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Brand Content',
    image: 'https://www.redbangle.com/wp-content/uploads/2021/02/logored.png',
    url: 'https://www.redbangle.com/',
    telephone: '9876543210',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress:
        '2nd Floor, Silver Rock, 12, Nandi Durga Road, 1, 1st Main Rd, Bengaluru, Karnataka',
      addressLocality: 'India',
      postalCode: '560046',
      addressCountry: 'IN',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 13.12032,
      longitude: 77.62527,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Brand Content',
    alternateName: 'Brand Content',
    url: 'https://www.redbangle.com/',
    logo: 'https://www.redbangle.com/wp-content/uploads/2021/02/logored.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '9876543210',
      contactType: 'sales',
      areaServed: 'IN',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.com/wp-content/uploads/2021/02/logored.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.com/',
      image: 'https://www.redbangle.com/wp-content/uploads/2021/02/logored.png',
    },
    headline: 'Brand Content',
    datePublished: '2011-01-28T17:15:23+08:00',
    dateModified: '2022-01-28T16:12:29+08:00',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Brand Content',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.com/wp-content/uploads/2021/02/logored.png',
      },
    },
  },
  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Global Team',
    image: 'https://www.redbangle.com/wp-content/uploads/2021/02/logored.png',
    url: 'https://www.redbangle.com/',
    telephone: '9876543210',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress:
        '2nd Floor, Silver Rock, 12, Nandi Durga Road, 1, 1st Main Rd, Bengaluru, Karnataka',
      addressLocality: 'India',
      postalCode: '560046',
      addressCountry: 'IN',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 13.12032,
      longitude: 77.62527,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Global Team',
    alternateName: 'Global Team',
    url: 'https://www.redbangle.com/',
    logo: 'https://www.redbangle.com/wp-content/uploads/2021/02/logored.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '9876543210',
      contactType: 'sales',
      areaServed: 'IN',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.com/wp-content/uploads/2021/02/logored.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.com/',
      image: 'https://www.redbangle.com/wp-content/uploads/2021/02/logored.png',
    },
    headline: 'Global Team',
    datePublished: '2011-01-28T17:15:23+08:00',
    dateModified: '2022-01-28T16:12:29+08:00',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Global Team',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.com/wp-content/uploads/2021/02/logored.png',
      },
    },
  },

  {
    '@context': 'https://schema.org/',
    '@type': 'BreadcrumbList',
    itemListElement: [
      {
        '@type': 'ListItem',
        position: 1,
        name: 'Brand Content',
        item: 'https://www.redbangle.com/',
      },
      {
        '@type': 'ListItem',
        position: 2,
        name: 'Advertising Agency',
        item: 'https://www.redbangle.com/',
      },
      {
        '@type': 'ListItem',
        position: 3,
        name: 'Digital Marketing Company',
        item: 'https://www.redbangle.com/',
      },
      {
        '@type': 'ListItem',
        position: 4,
        name: 'Creative Agency',
        item: 'https://www.redbangle.com/',
      },
      {
        '@type': 'ListItem',
        position: 5,
        name: 'Integrated Agency',
        item: 'https://www.redbangle.com/',
      },
      {
        '@type': 'ListItem',
        position: 6,
        name: 'Content Production Agency',
        item: 'https://www.redbangle.com/',
      },
      {
        '@type': 'ListItem',
        position: 7,
        name: 'Brand Strategy',
        item: 'https://www.redbangle.com/',
      },
      {
        '@type': 'ListItem',
        position: 8,
        name: 'Holistic Marketing Agency',
        item: 'https://www.redbangle.com/',
      },
      {
        '@type': 'ListItem',
        position: 9,
        name: 'Integrated Marketing Agency',
        item: 'https://www.redbangle.com/',
      },
      {
        '@type': 'ListItem',
        position: 10,
        name: 'Brand Content Production Agency',
        item: 'https://www.redbangle.com/',
      },
      {
        '@type': 'ListItem',
        position: 11,
        name: 'Brand Content Production Agency',
        item: 'https://www.redbangle.com/creative-agency-services-for-brand-content',
      },
      {
        '@type': 'ListItem',
        position: 12,
        name: 'Integrated Marketing Agency',
        item: 'https://www.redbangle.com/brand-content-production-agency',
      },
      {
        '@type': 'ListItem',
        position: 13,
        name: 'Holistic Marketing Agency',
        item: 'https://www.redbangle.com/brand-content-production-agency',
      },
      {
        '@type': 'ListItem',
        position: 14,
        name: 'Brand Strategy',
        item: 'https://www.redbangle.com/brand-content-production-agency',
      },
      {
        '@type': 'ListItem',
        position: 15,
        name: 'Content Production Agency',
        item: 'https://www.redbangle.com/brand-content-production-agency',
      },
      {
        '@type': 'ListItem',
        position: 16,
        name: 'Integrated Agency',
        item: 'https://www.redbangle.com/brand-content-production-agency',
      },
      {
        '@type': 'ListItem',
        position: 17,
        name: 'Creative Agency',
        item: 'https://www.redbangle.com/brand-content-production-agency',
      },
      {
        '@type': 'ListItem',
        position: 18,
        name: 'Digital Marketing Company',
        item: 'https://www.redbangle.com/brand-content-production-agency',
      },
      {
        '@type': 'ListItem',
        position: 19,
        name: 'Advertising Agency',
        item: 'https://www.redbangle.com/brand-content-production-agency',
      },
      {
        '@type': 'ListItem',
        position: 20,
        name: 'Global Team',
        item: 'https://www.redbangle.com/brand-content-production-agency',
      },
      {
        '@type': 'ListItem',
        position: 21,
        name: 'Brand Content',
        item: 'https://www.redbangle.com/brand-content-production-agency',
      },
      {
        '@type': 'ListItem',
        position: 22,
        name: 'Integrated Marketing Agency Expertise',
        item: 'https://www.redbangle.com/creative-agency-services-for-brand-content',
      },
      {
        '@type': 'ListItem',
        position: 23,
        name: 'Holistic Marketing Agency Solutions',
        item: 'https://www.redbangle.com/creative-agency-services-for-brand-content',
      },
      {
        '@type': 'ListItem',
        position: 24,
        name: 'Brand Strategy Services',
        item: 'https://www.redbangle.com/creative-agency-services-for-brand-content',
      },
      {
        '@type': 'ListItem',
        position: 25,
        name: 'Content Production Agency',
        item: 'https://www.redbangle.com/creative-agency-services-for-brand-content',
      },
      {
        '@type': 'ListItem',
        position: 26,
        name: 'Brand Strategy Solutions',
        item: 'https://www.redbangle.com/creative-agency-services-for-brand-content',
      },
      {
        '@type': 'ListItem',
        position: 27,
        name: 'Content Production Services',
        item: 'https://www.redbangle.com/creative-agency-services-for-brand-content',
      },
      {
        '@type': 'ListItem',
        position: 28,
        name: 'Content Production Solutions',
        item: 'https://www.redbangle.com/creative-agency-services-for-brand-content',
      },
      {
        '@type': 'ListItem',
        position: 29,
        name: 'Content Production Expertise',
        item: 'https://www.redbangle.com/creative-agency-services-for-brand-content',
      },
      {
        '@type': 'ListItem',
        position: 30,
        name: 'Creative Agency',
        item: 'https://www.redbangle.com/creative-agency-services-for-brand-content',
      },
      {
        '@type': 'ListItem',
        position: 31,
        name: 'Best Creative Agency Service',
        item: 'https://www.redbangle.com/creative-agency-services-for-brand-content',
      },
      {
        '@type': 'ListItem',
        position: 32,
        name: 'Integrated Marketing Agency',
        item: 'https://www.redbangle.com/integrated-marketing-agency-for-successful-campaigns',
      },
      {
        '@type': 'ListItem',
        position: 33,
        name: 'Integrated Marketing Solutions',
        item: 'https://www.redbangle.com/integrated-marketing-agency-for-successful-campaigns',
      },
      {
        '@type': 'ListItem',
        position: 34,
        name: 'Internet Marketing Agency',
        item: 'https://www.redbangle.com/integrated-marketing-agency-for-successful-campaigns',
      },
      {
        '@type': 'ListItem',
        position: 35,
        name: 'Successful Campaigns',
        item: 'https://www.redbangle.com/integrated-marketing-agency-for-successful-campaigns',
      },
      {
        '@type': 'ListItem',
        position: 36,
        name: 'Digital Marketing Solutions',
        item: 'https://www.redbangle.com/integrated-marketing-agency-for-successful-campaigns',
      },
      {
        '@type': 'ListItem',
        position: 37,
        name: 'Brand Growth',
        item: 'https://www.redbangle.com/integrated-marketing-agency-for-successful-campaigns',
      },
      {
        '@type': 'ListItem',
        position: 38,
        name: 'Full Service Advertising Agency',
        item: 'https://www.redbangle.com/integrated-marketing-agency-for-successful-campaigns',
      },
      {
        '@type': 'ListItem',
        position: 39,
        name: 'Marketing Agency',
        item: 'https://www.redbangle.com/holistic-marketing-agency-for-creative-content-marketing',
      },
      {
        '@type': 'ListItem',
        position: 40,
        name: 'Holistic Marketing',
        item: 'https://www.redbangle.com/holistic-marketing-agency-for-creative-content-marketing',
      },
      {
        '@type': 'ListItem',
        position: 41,
        name: 'Marketing Content Strategy',
        item: 'https://www.redbangle.com/holistic-marketing-agency-for-creative-content-marketing',
      },
      {
        '@type': 'ListItem',
        position: 42,
        name: 'Digital Brand Management',
        item: 'https://www.redbangle.com/holistic-marketing-agency-for-creative-content-marketing',
      },
      {
        '@type': 'ListItem',
        position: 43,
        name: 'Creative Content Marketing',
        item: 'https://www.redbangle.com/holistic-marketing-agency-for-creative-content-marketing',
      },
      {
        '@type': 'ListItem',
        position: 44,
        name: 'Marketing Agency Near Me',
        item: 'https://www.redbangle.com/holistic-marketing-agency-for-creative-content-marketing',
      },
      {
        '@type': 'ListItem',
        position: 45,
        name: 'Digital Media Marketing',
        item: 'https://www.redbangle.com/holistic-marketing-agency-for-creative-content-marketing',
      },
      {
        '@type': 'ListItem',
        position: 46,
        name: 'Content Marketing Strategy',
        item: 'https://www.redbangle.com/holistic-marketing-agency-for-creative-content-marketing',
      },
      {
        '@type': 'ListItem',
        position: 47,
        name: 'Full Service Advertising Agency',
        item: 'https://www.redbangle.com/holistic-marketing-agency-for-creative-content-marketing',
      },
      {
        '@type': 'ListItem',
        position: 48,
        name: 'Video Production Company',
        item: 'https://www.redbangle.com/video-production-company-for-corporate-storytelling',
      },
      {
        '@type': 'ListItem',
        position: 49,
        name: 'Animation Video Company',
        item: 'https://www.redbangle.com/video-production-company-for-corporate-storytelling',
      },
      {
        '@type': 'ListItem',
        position: 50,
        name: 'Video Content Production',
        item: 'https://www.redbangle.com/video-production-company-for-corporate-storytelling',
      },
      {
        '@type': 'ListItem',
        position: 51,
        name: 'Visual Storytelling',
        item: 'https://www.redbangle.com/video-production-company-for-corporate-storytelling',
      },
      {
        '@type': 'ListItem',
        position: 52,
        name: 'Animation Projects',
        item: 'https://www.redbangle.com/video-production-company-for-corporate-storytelling',
      },
      {
        '@type': 'ListItem',
        position: 53,
        name: 'Engaging Videos',
        item: 'https://www.redbangle.com/video-production-company-for-corporate-storytelling',
      },
      {
        '@type': 'ListItem',
        position: 54,
        name: 'Corporate Storytelling',
        item: 'https://www.redbangle.com/video-production-company-for-corporate-storytelling',
      },
      {
        '@type': 'ListItem',
        position: 55,
        name: 'Video Marketing Solutions',
        item: 'https://www.redbangle.com/video-production-company-for-corporate-storytelling',
      },
      {
        '@type': 'ListItem',
        position: 56,
        name: 'Video Production Company',
        item: 'https://www.redbangle.com/video-production-agency-for-corporate-video',
      },
      {
        '@type': 'ListItem',
        position: 57,
        name: 'Animation Video Company',
        item: 'https://www.redbangle.com/video-production-agency-for-corporate-video',
      },
      {
        '@type': 'ListItem',
        position: 58,
        name: 'Video Content Production',
        item: 'https://www.redbangle.com/video-production-agency-for-corporate-video',
      },
      {
        '@type': 'ListItem',
        position: 59,
        name: 'Visual Storytelling',
        item: 'https://www.redbangle.com/video-production-agency-for-corporate-video',
      },
      {
        '@type': 'ListItem',
        position: 60,
        name: 'Animation Projects',
        item: 'https://www.redbangle.com/video-production-agency-for-corporate-video',
      },
      {
        '@type': 'ListItem',
        position: 61,
        name: 'Engaging Videos',
        item: 'https://www.redbangle.com/video-production-agency-for-corporate-video',
      },
      {
        '@type': 'ListItem',
        position: 62,
        name: 'Corporate Storytelling',
        item: 'https://www.redbangle.com/video-production-agency-for-corporate-video',
      },
      {
        '@type': 'ListItem',
        position: 63,
        name: 'Video Marketing Solutions',
        item: 'https://www.redbangle.com/video-production-agency-for-corporate-video',
      },
      {
        '@type': 'ListItem',
        position: 64,
        name: 'Video Production Agency',
        item: 'https://www.redbangle.com/video-production-agency-for-corporate-video',
      },
      {
        '@type': 'ListItem',
        position: 65,
        name: 'Brand Promotions',
        item: 'https://www.redbangle.com/creative-campaigns-for-brand-promotions',
      },
      {
        '@type': 'ListItem',
        position: 66,
        name: 'Creative Agency',
        item: 'https://www.redbangle.com/creative-campaigns-for-brand-promotions',
      },
      {
        '@type': 'ListItem',
        position: 67,
        name: 'Creative Campaigns',
        item: 'https://www.redbangle.com/creative-campaigns-for-brand-promotions',
      },
      {
        '@type': 'ListItem',
        position: 68,
        name: 'Ad Campaigns',
        item: 'https://www.redbangle.com/creative-campaigns-for-brand-promotions',
      },
      {
        '@type': 'ListItem',
        position: 69,
        name: 'Advertising Solutions',
        item: 'https://www.redbangle.com/creative-campaigns-for-brand-promotions',
      },
      {
        '@type': 'ListItem',
        position: 70,
        name: 'Content Marketing Strategy',
        item: 'https://www.redbangle.com/creative-marketing-agency-for-brand-campaigns',
      },
      {
        '@type': 'ListItem',
        position: 71,
        name: 'Best Creative Agency',
        item: 'https://www.redbangle.com/creative-marketing-agency-for-brand-campaigns',
      },
      {
        '@type': 'ListItem',
        position: 72,
        name: 'Digital Brand Management',
        item: 'https://www.redbangle.com/creative-marketing-agency-for-brand-campaigns',
      },
      {
        '@type': 'ListItem',
        position: 73,
        name: 'Creative Content Marketing',
        item: 'https://www.redbangle.com/creative-marketing-agency-for-brand-campaigns',
      },
      {
        '@type': 'ListItem',
        position: 74,
        name: 'Marketing Agency Near Me',
        item: 'https://www.redbangle.com/creative-marketing-agency-for-brand-campaigns',
      },
      {
        '@type': 'ListItem',
        position: 75,
        name: 'Digital Media Marketing',
        item: 'https://www.redbangle.com/creative-marketing-agency-for-brand-campaigns',
      },
      {
        '@type': 'ListItem',
        position: 76,
        name: 'Content Marketing Strategy',
        item: 'https://www.redbangle.com/creative-marketing-agency-for-brand-campaigns',
      },
      {
        '@type': 'ListItem',
        position: 77,
        name: 'Brand campaigns',
        item: 'https://www.redbangle.com/creative-marketing-agency-for-brand-campaigns',
      },
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'SiteNavigationElement',
    hasPart: [
      {
        '@context': 'https://schema.org',
        '@type': 'WebPage',
        url: '/brand-content-production-agency',
      },
      {
        '@context': 'https://schema.org',
        '@type': 'WebPage',
        url: '/creative-agency-services-for-brand-content',
      },
      {
        '@context': 'https://schema.org',
        '@type': 'WebPage',
        url: '/join-our-team-of-creative-marketing-experts',
      },
      {
        '@context': 'https://schema.org',
        '@type': 'WebPage',
        url: '/global-team-for-holistic-marketing',
      },
      {
        '@context': 'https://schema.org',
        '@type': 'WebPage',
        url: '/integrated-marketing-agency-for-successful-campaigns',
      },
      {
        '@context': 'https://schema.org',
        '@type': 'WebPage',
        url: '/holistic-marketing-agency-for-creative-content-marketing',
      },
      {
        '@context': 'https://schema.org',
        '@type': 'WebPage',
        url: '/video-production-company-for-corporate-storytelling',
      },
      {
        '@context': 'https://schema.org',
        '@type': 'WebPage',
        url: '/video-production-agency-for-corporate-video',
      },
      {
        '@context': 'https://schema.org',
        '@type': 'WebPage',
        url: '/creative-campaigns-for-brand-promotions',
      },
      {
        '@context': 'https://schema.org',
        '@type': 'WebPage',
        url: '/creative-marketing-agency-for-brand-campaigns',
      },
      {
        '@context': 'https://schema.org',
        '@type': 'WebPage',
        url: '/collaborators-for-creative-marketing-and-digital-campaigns',
      },
      {
        '@context': 'https://schema.org',
        '@type': 'WebPage',
        url: '/marketing-blogs-brand-content-resources',
      },
      {
        '@context': 'https://schema.org',
        '@type': 'WebPage',
        url: '/unleash-your-creative-vision-ideas-into-action',
      },
      {
        '@context': 'https://schema.org',
        '@type': 'WebPage',
        url: '/contact-your-brand-strategy-solutions-provider',
      },
    ],
  },

  {
    '@context': 'https://schema.org',
    '@graph': [
      {
        '@context': 'https://schema.org',
        '@type': 'SiteNavigationElement',
        id: 'site-navigation',
        name: 'Brand Content Production Agency | Integrated Marketing Agency | Holistic Marketing Agency | Brand Strategy | Content Production Agency | Integrated Agency | Creative Agency | Digital Marketing Company | Advertising Agency | Brand Content',
        url: 'https://www.redbangle.com/',
      },
      {
        '@context': 'https://schema.org',
        '@type': 'SiteNavigationElement',
        id: 'site-navigation',
        name: 'Brand Content Production Agency | Integrated Marketing Agency | Holistic Marketing Agency | Brand Strategy | Content Production Agency | Integrated Agency | Creative Agency | Digital Marketing Company | Advertising Agency | Global Team | Brand Content',
        url: 'https://www.redbangle.com/brand-content-production-agency/',
      },
      {
        '@context': 'https://schema.org',
        '@type': 'SiteNavigationElement',
        id: 'site-navigation',
        name: 'Integrated Marketing Agency Expertise| Holistic Marketing Agency Solutions | Brand Strategy Services | Content Production Agency | Brand Strategy Solutions | Content Production Services | Content Production Solutions | Content Production Expertise | What We Do | Creative Agency | Best Creative Agency Service',
        url: 'https://www.redbangle.com/creative-agency-services-for-brand-content/',
      },
      {
        '@context': 'https://schema.org',
        '@type': 'SiteNavigationElement',
        id: 'site-navigation',
        name: 'Career Opportunities in Advertising Agency | Join Our Team of Creative Marketing experts | Employment At Red Bangle | Job Openings in Creative Marketing and Digital Campaign | Work With Us in Creative Agency | Careers In Marketing Digital Campaign | Career Development in Creative Marketing | Team Culture in Advertising Agency | Apply Now for Creative Marketing career | Hiring Digital Campaign experts',
        url: 'https://www.redbangle.com/join-our-team-of-creative-marketing-experts/',
      },
      {
        '@context': 'https://schema.org',
        '@type': 'SiteNavigationElement',
        id: 'site-navigation',
        name: 'Global Team for Holistic Marketing | International Experts Marketing Agency | Diverse Professionals for Marketing Content Strategy | Meet Our Team | Multicultural Team for Digital Brand Management | Global Expertise Marketing Content Strategy | Team Members Marketing Agency | International Presence | Collaborative Team for Creative Content Marketing | Our People',
        url: 'https://www.redbangle.com/global-team-for-holistic-marketing/',
      },
      {
        '@context': 'https://schema.org',
        '@type': 'SiteNavigationElement',
        id: 'site-navigation',
        name: 'Integrated Marketing Agency | Integrated Marketing Solutions | Internet Marketing Agency | Successful Campaigns | Digital Marketing Solutions | Brand Growth | Full Service Advertising Agency',
        url: 'https://www.redbangle.com/integrated-marketing-agency-for-successful-campaigns/',
      },
      {
        '@context': 'https://schema.org',
        '@type': 'SiteNavigationElement',
        id: 'site-navigation',
        name: 'Marketing Agency | Holistic Marketing | Marketing Content Strategy| Digital Brand Management | Creative Content Marketing | Marketing Agency Near Me | Digital Media Marketing | Content Marketing Strategy | Full Service Advertising Agency',
        url: 'https://www.redbangle.com/holistic-marketing-agency-for-creative-content-marketing/',
      },
      {
        '@context': 'https://schema.org',
        '@type': 'SiteNavigationElement',
        id: 'site-navigation',
        name: 'Video Production Company | Animation Video Company | Video Content Production | Visual Storytelling | Animation Projects | Engaging Videos | Corporate Storytelling | Video Marketing Solutions',
        url: 'https://www.redbangle.com/video-production-company-for-corporate-storytelling/',
      },
      {
        '@context': 'https://schema.org',
        '@type': 'SiteNavigationElement',
        id: 'site-navigation',
        name: 'Video Production Company | Animation Video Company | Video Content Production | Visual Storytelling | Animation Projects | Engaging Videos | Corporate Storytelling | Video Marketing Solutions | Video Production Agency',
        url: 'https://www.redbangle.com/video-production-agency-for-corporate-video/',
      },
      {
        '@context': 'https://schema.org',
        '@type': 'SiteNavigationElement',
        id: 'site-navigation',
        name: 'Creative Agency | Creative Campaigns | Brand Promotions | Ad Campaigns| Advertising Solutions',
        url: 'https://www.redbangle.com/creative-campaigns-for-brand-promotions/',
      },
      {
        '@context': 'https://schema.org',
        '@type': 'SiteNavigationElement',
        id: 'site-navigation',
        name: 'Content Marketing Strategy | Best Creative Agency | Digital Brand Management | Creative Content Marketing | Marketing Agency Near Me | Digital Media Marketing | Content Marketing Strategy | Brand campaigns',
        url: 'https://www.redbangle.com/creative-marketing-agency-for-brand-campaigns/',
      },
      {
        '@context': 'https://schema.org',
        '@type': 'SiteNavigationElement',
        id: 'site-navigation',
        name: 'Be a successful Collaborator with Advertising Agency | Join Our Team of Creative Marketing experts | Be a successful Collaborator with Red Bangle | Collaborators for Creative Marketing and Digital Campaign | Work With Us in Creative Agency as a Collaborators | Marketing Digital Campaign Collaborators | Career Development in Creative Marketing | Join our Global Network of Collaborators',
        url: 'https://www.redbangle.com/collaborators-for-creative-marketing-and-digital-campaigns/',
      },
      {
        '@context': 'https://schema.org',
        '@type': 'SiteNavigationElement',
        id: 'site-navigation',
        name: 'Explore the World of Red Bangle Productions | Read our latest Articles | Stay updated with Latest News and Insights | Marketing Blogs Content Marketing Insights | Brand Content Resources',
        url: 'https://www.redbangle.com/marketing-blogs-brand-content-resources/',
      },
      {
        '@context': 'https://schema.org',
        '@type': 'SiteNavigationElement',
        id: 'site-navigation',
        name: 'Unleash your Creative Vision into action | Transform ideas into Action | Give shape to your Ideas with Red Bangle | Transform ideas into Designs',
        url: 'https://www.redbangle.com/unleash-your-creative-vision-ideas-into-action/',
      },
      {
        '@context': 'https://schema.org',
        '@type': 'SiteNavigationElement',
        id: 'site-navigation',
        name: 'Contact your Holistic Marketing Agency | Meet your Content Production Agency | Contact your Brand Strategy Solutions provider | Reach your Content Production Services provider | Contact your Content Production Solutions provider',
        url: 'https://www.redbangle.com/contact-your-brand-strategy-solutions-provider/',
      },
    ],
  },

  {
    '@context': 'https://schema.org',
    '@graph': [
      {
        '@context': 'https://schema.org',
        '@type': 'SiteNavigationElement',
        '@id': '#table-of-contents',
        name: 'Brand Content Production Agency | Integrated Marketing Agency | Holistic Marketing Agency | Brand Strategy | Content Production Agency | Integrated Agency | Creative Agency | Digital Marketing Company | Advertising Agency | Brand Content',
        url: 'https://www.redbangle.com/',
      },
      {
        '@context': 'https://schema.org',
        '@type': 'SiteNavigationElement',
        '@id': '#table-of-contents',
        name: 'Brand Content Production Agency | Integrated Marketing Agency | Holistic Marketing Agency | Brand Strategy | Content Production Agency | Integrated Agency | Creative Agency | Digital Marketing Company | Advertising Agency | Global Team | Brand Content',
        url: 'https://www.redbangle.com/brand-content-production-agency',
      },
      {
        '@context': 'https://schema.org',
        '@type': 'SiteNavigationElement',
        '@id': '#table-of-contents',
        name: 'Integrated Marketing Agency Expertise| Holistic Marketing Agency Solutions | Brand Strategy Services | Content Production Agency | Brand Strategy Solutions | Content Production Services | Content Production Solutions | Content Production Expertise | What We Do | Creative Agency | Best Creative Agency Service',
        url: 'https://www.redbangle.com/creative-agency-services-for-brand-content',
      },
      {
        '@context': 'https://schema.org',
        '@type': 'SiteNavigationElement',
        '@id': '#table-of-contents',
        name: 'Career Opportunities in Advertising Agency | Join Our Team of Creative Marketing experts | Employment At Red Bangle | Job Openings in Creative Marketing and Digital Campaign | Work With Us in Creative Agency | Careers In Marketing Digital Campaign | Career Development in Creative Marketing | Team Culture in Advertising Agency | Apply Now for Creative Marketing career | Hiring Digital Campaign experts',
        url: 'https://www.redbangle.com/join-our-team-of-creative-marketing-experts',
      },
      {
        '@context': 'https://schema.org',
        '@type': 'SiteNavigationElement',
        '@id': '#table-of-contents',
        name: 'Global Team for Holistic Marketing | International Experts Marketing Agency | Diverse Professionals for Marketing Content Strategy | Meet Our Team | Multicultural Team for Digital Brand Management | Global Expertise Marketing Content Strategy | Team Members Marketing Agency | International Presence | Collaborative Team for Creative Content Marketing | Our People',
        url: 'https://www.redbangle.com/global-team-for-holistic-marketing',
      },
      {
        '@context': 'https://schema.org',
        '@type': 'SiteNavigationElement',
        '@id': '#table-of-contents',
        name: 'Integrated Marketing Agency | Integrated Marketing Solutions | Internet Marketing Agency | Successful Campaigns | Digital Marketing Solutions | Brand Growth | Full Service Advertising Agency',
        url: 'https://www.redbangle.com/integrated-marketing-agency-for-successful-campaigns',
      },
      {
        '@context': 'https://schema.org',
        '@type': 'SiteNavigationElement',
        '@id': '#table-of-contents',
        name: 'Marketing Agency | Holistic Marketing | Marketing Content Strategy| Digital Brand Management | Creative Content Marketing | Marketing Agency Near Me | Digital Media Marketing | Content Marketing Strategy | Full Service Advertising Agency',
        url: 'https://www.redbangle.com/holistic-marketing-agency-for-creative-content-marketing',
      },
      {
        '@context': 'https://schema.org',
        '@type': 'SiteNavigationElement',
        '@id': '#table-of-contents',
        name: 'Video Production Company | Animation Video Company | Video Content Production | Visual Storytelling | Animation Projects | Engaging Videos | Corporate Storytelling | Video Marketing Solutions',
        url: 'https://www.redbangle.com/video-production-company-for-corporate-storytelling',
      },
      {
        '@context': 'https://schema.org',
        '@type': 'SiteNavigationElement',
        '@id': '#table-of-contents',
        name: 'Video Production Company | Animation Video Company | Video Content Production | Visual Storytelling | Animation Projects | Engaging Videos | Corporate Storytelling | Video Marketing Solutions | Video Production Agency',
        url: 'https://www.redbangle.com/video-production-agency-for-corporate-video',
      },
      {
        '@context': 'https://schema.org',
        '@type': 'SiteNavigationElement',
        '@id': '#table-of-contents',
        name: 'Creative Agency | Creative Campaigns | Brand Promotions | Ad Campaigns| Advertising Solutions',
        url: 'https://www.redbangle.com/creative-campaigns-for-brand-promotions',
      },
      {
        '@context': 'https://schema.org',
        '@type': 'SiteNavigationElement',
        '@id': '#table-of-contents',
        name: 'Content Marketing Strategy | Best Creative Agency | Digital Brand Management | Creative Content Marketing | Marketing Agency Near Me | Digital Media Marketing | Content Marketing Strategy | Brand campaigns',
        url: 'https://www.redbangle.com/creative-marketing-agency-for-brand-campaigns',
      },
      {
        '@context': 'https://schema.org',
        '@type': 'SiteNavigationElement',
        '@id': '#table-of-contents',
        name: 'Be a successful Collaborator with Advertising Agency | Join Our Team of Creative Marketing experts | Be a successful Collaborator with Red Bangle | Collaborators for Creative Marketing and Digital Campaign | Work With Us in Creative Agency as a Collaborators | Marketing Digital Campaign Collaborators | Career Development in Creative Marketing | Join our Global Network of Collaborators',
        url: 'https://www.redbangle.com/collaborators-for-creative-marketing-and-digital-campaigns',
      },
      {
        '@context': 'https://schema.org',
        '@type': 'SiteNavigationElement',
        '@id': '#table-of-contents',
        name: 'Explore the World of Red Bangle Productions | Read our latest Articles | Stay updated with Latest News and Insights | Marketing Blogs Content Marketing Insights | Brand Content Resources',
        url: 'https://www.redbangle.com/marketing-blogs-brand-content-resources',
      },
      {
        '@context': 'https://schema.org',
        '@type': 'SiteNavigationElement',
        '@id': '#table-of-contents',
        name: 'Unleash your Creative Vision into action | Transform ideas into Action | Give shape to your Ideas with Red Bangle | Transform ideas into Designs',
        url: 'https://www.redbangle.com/unleash-your-creative-vision-ideas-into-action',
      },
      {
        '@context': 'https://schema.org',
        '@type': 'SiteNavigationElement',
        '@id': '#table-of-contents',
        name: 'Contact your Holistic Marketing Agency | Meet your Content Production Agency | Contact your Brand Strategy Solutions provider | Reach your Content Production Services provider | Contact your Content Production Solutions provider',
        url: 'https://www.redbangle.com/contact-your-brand-strategy-solutions-provider',
      },
    ],
  },
]
